barber/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from haircut import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$',views.index,name='index'),
    url(r'haircut', include('haircut.urls'), name='haircut'),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

haircut/urls.py
from django.conf.urls import url
from haircut import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'haircut'

urlpatterns = [
    url(r'^contact/',views.contact,name="contact"),
    url(r'^gallery/',views.gallery,name="gallery"),
    url(r'^about/',views.about,name="about"),


]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

haircut/models.py
from django.db import models

class Haircut(models.Model):
    name = models.CharField(max_length=100)
    image = models.ImageField(upload_to="pics",blank=True, null=True)

    def __str__(self):
        return self.name

class Contact(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    number = models.CharField(max_length=50)
    comment = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.name

haircut/forms.py
from django import forms
from .models import Contact


class ContactForm(forms.ModelForm):
    class Meta:

        model = Contact
        fields = "__all__"

haircut/views.py
from django.shortcuts import render
from django.shortcuts import render
from .models import Haircut
from .forms import ContactForm
from . import forms
# Create your views here.
def index(request):
    barb = Haircut.objects.all()


    return render(request, "haircut/index.html",{"barb":barb})

def contact(request):

    form = forms.ContactForm()
    if request.method == 'POST':
        form = forms.ContactForm(request.POST)
        if form.is_valid():
            save_it = form.save(commit=False)
            save_it.save()
            return index(request)
    else:
        form = ContactForm

    return render(request, 'haircut/contact.html',{"form":form})


def gallery(request):

    return render(request, 'haircut/gallery.html')


def about(request):

    return render(request, 'haircut/about.html')

def price(request):

    return render(request, 'haircut/price.html')

templates/haircut/about.html
{% extends 'haircut/base.html'%}
  {% block content %}{% load static %}
  <div class="container">
    <div class="jumbotron">
          <h1 class="abt" style="font-size:500%";>About page</h1>
      <div class="row">
    <div class="column">
      <img src="{% static 'img/barb/b1.jpg' %}" alt="Snow" width="250" height="300" style="vertical-align:middle;margin:10px 0px">
    </div>
    <div class="column">
      <img src="{% static 'img/barb/b2.jpg' %}" alt="Forest" width="250" height="300" style="vertical-align:middle;margin:10px 5px">
    </div>
    <div class="column">
      <img src="{% static 'img/barb/g10.jpg' %}" alt="Mountains" width="250" height="300" style="vertical-align:middle;margin:10px 0px">
    </div>
    <div class="column">
      <img src="{% static 'img/barb/about-img2.jpg' %}" alt="Mountains" width="250" height="300" style="vertical-align:middle;margin:10px 5px">
    </div>
  </div>



<h5 style="font-family:serif;font-size:200%;">Our business has grown from humble beginnings to a brand customer are beginning to appreciate and idolize. We started off as a styling brand and later discovered that we also needed to fill in the void created by customers of all gender and race, to give them classic and lasting hair cuts that they always dreamt about and fantasized.
Our Mission Statement is to bring the fantasy of our esteemed clients to reality by delivering top-notch customer service to create life time lasting relationship with them. Knowing fully well that our business is basically founded on excellent customer delivery.
Our services include male and female hair styling/haircuts, fixing of extensions/weavons and coloring of hair.</h5>
  </div>
  </div>

{% endblock %}



<!--- <div class="col-lg-3 col-sm-6 col-md-3">
  <div class="single-service">
    <img class="img-fluid" src="{% static 'img/service/service2.jpg' %}" alt="">
    <h4>Quality Gel Shave</h4>
  </div>
</div>
<div class="col-lg-3 col-sm-6 col-md-3">
  <div class="single-service">
    <img class="img-fluid" src="{% static 'img/service/service3.jpg' %}" alt="">
    <h4>Beard Trimming</h4>
  </div>
</div>
<div class="col-lg-3 col-sm-6 col-md-3">
  <div class="single-service">
    <img class="img-fluid" src="{% static 'img/service/service4.jpg' %}" alt="">
    <h4>{{barb.name}}</h4>
  </div>
</div> -->

templates/haircut/base.html
{% include 'haircut/header.html' %}{% load static %}


{% block content %}

{% endblock %}

{% include 'haircut/footer.html' %}

templates/haircut/contact.html
{% extends 'haircut/base.html'%}
  {% block content %}
    <div class="container">
      <div class="jumbotron">
          <h1>Contact Form</h1>

          <form class="" method="post">
            {% csrf_token %}
            {{form.as_p}}

            <input type="submit" name="" value="Submit">

          </form>
        </div>
        </div>

{% endblock %}

templates/haircut/footer.html
<!--================ Start Footer Area =================-->
{% load static %}



  <!--<footer class="footer-area section-gap">-->
  <div class="container">
    <div class="row footer-inner">
    <div class="col-lg-5 col-sm-6">
        <aside class="f-widget">
          <div class="f-title">
            <h3>About Me</h3>
          </div>
          <p>Like a therapist, or the local barkeep, hairdressers are in a position of trust, We are transforming not just how a person looks but how they feel and, therefore, they want to tell us things.</p>

        </aside>
      </div>
      <div class="col-lg-5 col-sm-6">
        <aside class="f-widget news-widget">
          <div class="f-title">
            <h3>Newsletter</h3>
          </div>
          <p>Stay updated with our latest trends</p>
          <div id="mc_embed_signup">
            <form target="_blank" action="https://spondonit.us12.list-manage.com/subscribe/post?u=1462626880ade1ac87bd9c93a&amp;id=92a4423d01"
             method="get" class="subscribe_form relative">
              <div class="input-group d-flex flex-row">
                <input name="EMAIL" placeholder="Enter email address" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Email Address '"
                 required="" type="email">
                <button class="btn sub-btn"><span class="lnr lnr-arrow-right"></span></button>
              </div>
              <div class="mt-10 info"></div>
            </form>
          </div>
        </aside>
      </div>
      <div class="col-lg-2">
        <aside class="f-widget social-widget">
          <div class="f-title">
            <h3>Follow Me</h3>
          </div>
          <p>Let us be social</p>
          <ul class="list">
            <li><a href="https://www.facebook.com"><i class="fa fa-facebook"></i></a></li>
            <li><a href="https://www.instagram.com"><i class="fa fa-instagram"></i></a></li>

          </ul>
        </aside>
      </div>
    </div>
    <div class="row">

    </div>
  </div>
</footer>
<!--================ End Footer Area =================-->

<script src="{% static 'js/vendor/jquery-2.2.4.min.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4"
 crossorigin="anonymous"></script>
<script src="{% static 'js/vendor/bootstrap.min.js' %}"></script>
<script src="{% static 'js/owl.carousel.min.js ' %}"></script>
<script src="{% static 'js/owl-carousel-thumb.min.js'  %}"></script>
<script src="{% static 'js/jquery.sticky.js' %}"></script>
<script src="{% static 'js/jquery.tabs.min.js' %}"></script>
<script src="{% static 'js/parallax.min.js' %}"></script>
<script src="{% static 'js/jquery.nice-select.min.js' %}"></script>
<script src="{% static 'js/jquery.ajaxchimp.min.js' %}"></script>
<script src="{% static 'js/isotope.pkgd.min.js' %}"></script>
<script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBhOdIF3Y9382fqJYt5I_sswSrEw5eihAA"></script>
<script src="{% static 'js/bootstrap-datepicker.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>

templates/haircut/gallery.html
{% extends 'haircut/base.html'%}{% load static %}
  {% block content %}
  <div class="container">
    <div class="jumbotron">
<h1 style="color:black;text-align:center">Our Gallery</h1>

<div class="row">
<div class="column">
<img src="{% static 'img/barb/gl4.jpg' %}" alt="Snow" width="263" height="300" style="vertical-align:middle;margin:0px -15px">
</div>
<div class="column">
<img src="{% static 'img/barb/gl3.png' %}" alt="Forest" width="263" height="300" style="vertical-align:middle;margin:0px 5px" >
</div>
<div class="column">
<img src="{% static 'img/barb/g19.png' %}" alt="Mountains" width="263" height="300" style="vertical-align:middle;margin:0px 0px">
</div>
<div class="column">
<img src="{% static 'img/barb/gl1.jpg' %}" alt="Mountains" width="263" height="300" style="vertical-align:middle;margin:0px 5px" >
</div>

<h3></h3>
<div class="row">
<div class="column">
<img src="{% static 'img/barb/g30.jpg' %}" alt="Snow" width="263" height="350" style="vertical-align:middle;margin:10px 0px" >
</div>
<div class="column">
<img src="{% static 'img/barb/g28.jpg' %}" alt="Forest" width="263" height="350"style="vertical-align:middle;margin:10px 5px" >
</div>
<div class="column">
<img src="{% static 'img/barb/g26.jpg' %}" alt="Mountains" width="263" height="350" style="vertical-align:middle;margin:10px 5px" >
</div>
<div class="column">
<img src="{% static 'img/barb/g25.jpg' %}" alt="Mountains" width="263" height="350" style="vertical-align:middle;margin:10px 5px" >
</div>

<div class="row">
<div class="column">
<img src="{% static 'img/barb/g14.jpg' %}" alt="Snow" width="263" height="300" style="vertical-align:middle;margin:10px 10px" >
</div>
<div class="column">
<img src="{% static 'img/barb/g15.jpg' %}" alt="Forest" width="263" height="300"style="vertical-align:middle;margin:10px 5px" >
</div>
<div class="column">
<img src="{% static 'img/barb/g20.jpg' %}" alt="Mountains" width="263" height="300" style="vertical-align:middle;margin:10px 5px" >
</div>
<div class="column">
<img src="{% static 'img/barb/g16.jpg' %}" alt="Mountains" width="263" height="300" style="vertical-align:middle;margin:10px 5px" >
</div>

</div>
</div>

{% endblock %}

templates/haircut/header.html
<!DOCTYPE html>
{% load static %}
<html lang="zxx" class="no-js">

<head>
	<!-- Mobile Specific Meta -->
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<!-- Favicon-->
	<link rel="shortcut icon" href="img/fav.png">
	<!-- Author Meta -->
	<meta name="author" content="CodePixar">
	<!-- Meta Description -->
	<meta name="description" content="">
	<!-- Meta Keyword -->
	<meta name="keywords" content="">
	<!-- meta character set -->
	<meta charset="UTF-8">
	<!-- Site Title -->
	<title>Barcut Salon</title>

	<link href="https://fonts.googleapis.com/css?family=Playfair+Display:400,700|Roboto:400,500,500i" rel="stylesheet">
	<!--
			CSS
			============================================= -->
	<link rel="stylesheet" href="{% static 'css/linearicons.css' %}">
	<link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
	<link rel="stylesheet" href="{% static 'css/availability-calendar.css' %}">
	<link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
	<link rel="stylesheet" href="{% static 'css/nice-select.css' %}">
	<link rel="stylesheet" href="{% static 'css/owl.carousel.css' %}">
	<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
	<link rel="stylesheet" href="{% static 'css/bootstrap-datepicker.css' %}">
	<link rel="stylesheet" href="{% static 'css/main.css' %}">
  <link rel="stylesheet" href="{% static 'css/about.css' %}">
</head>

<body>

	<!--================ Start Header Area =================-->
	<header class="header-area">
		<div class="container">
			<div class="header-wrap">
				<div class="header-top d-flex justify-content-between align-items-center navbar-expand-lg">
					<div class="col menu-left">
						<a class="active" href="{% url 'index' %}">Home</a>
						<a href="{% url 'haircut:about' %}">about</a>

						<a href="{% url 'haircut:gallery' %}">gallery</a>
					</div>
					<div class="col-3 logo">
						<a href="{% url 'index' %}"><img class="mx-auto" src="{% static 'img/log.png' %}" alt=""></a>
					</div>
					<nav class="col navbar navbar-expand-lg justify-content-end">

						<!-- Toggler/collapsibe Button -->
						<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
							<span class="lnr lnr-menu"></span>
						</button>

						<!-- Navbar links -->
						<div class="collapse navbar-collapse menu-right" id="collapsibleNavbar">
							<ul class="navbar-nav justify-content-center w-100">
								<li class="nav-item hide-lg">
									<a class="nav-link" href="{% url 'index' %}">Home</a>
								</li>
								<li class="nav-item hide-lg">
									<a class="nav-link" href="{% url 'haircut:about' %}">about</a>
								</li>


								<li class="nav-item hide-lg">
									<a class="nav-link" href="{% url 'haircut:gallery' %}">gallery</a>
								</li>
								<!-- Dropdown -->

								<li class="nav-item">
									<a class="nav-link" href="{% url 'haircut:contact' %}">Contact</a>
								</li>

							</ul>
              <aside class="">
                <ul class="list">
                  <li><a href="https://www.facebook.com/eltarisalon/"><i class="fa fa-facebook"></i></a></li>
                  <li><a href="https://www.instagram.com/eltarisalon/?hl=pl"><i class="fa fa-instagram"></i></a></li>

                </ul>
              </aside>

						</div>
					</nav>
				</div>
			</div>
		</div>
	</header>

</body>

</html>
	<!--================ End Header Area =================-->

templates/haircut/index.html
{% extends 'haircut/base.html' %}{% load static %}
 {% block content %}
	<!--================ Start banner Area =================-->
	<section class="home-banner-area relative">
		<div class="owl-carousel home-banner-owl">
			<div class="banner-img">
				<img class="img-fluid" src="{% static 'img/banner/b1.jpg' %}" alt="No">
				<div class="overlay overlay-bg"></div>
			</div>
			<div class="banner-img">
				<img class="img-fluid" src="{% static 'img/banner/b2.jpg' %}" alt="">
				<div class="overlay overlay-bg"></div>
			</div>
			<div class="banner-img">
			<img class="img-fluid" src="{% static 'img/banner/b3.jpg' %}" alt=""
				<div class="overlay overlay-bg"></div>
			</div>
		</div>

		<div class="text-wrapper">
			<h1>
				For All Occasion <br>
				Eltari Salon is a Must Try
			</h1>


			<div class="video-text">

			</div>
		</div>
	</section>
	<!--================ End banner Area =================-->

	<!--================ Start About Area =================-->
	<section class="section-gap-top about-area">
		<div class="container">
			<div class="single-about row align-items-center">
				<div class="col-lg-4 col-md-6 no-padding about-left">
					<div class="about-content">
						<h1>We Believe that <br> Interior beauty Lasts Long</h1>

						<a href="{% url 'haircut:gallery' %}" class="primary-btn">More Photos</a>
					</div>
				</div>
				<div class="col-lg-7 col-md-6 text-center no-padding about-right">
					<div class="about-thumb">
						<img src="{% static 'img/barb/g23.jpg' %}" class="img-fluid info-img" alt="">
					</div>
				</div>
				<div class="bordered-img">
					<img src="{% static 'img/barb/b2.jpg'  %}" class="img-fluid info-img" alt="">
				</div>
			</div>
		</div>
	</section>
	<!--================ End About Area =================-->

	<!--================ Start Service Area =================-->
	<section class="service-area section-gap">
		<div class="container">
			<div class="row justify-content-center">
				<div class="col-md-8 text-center">
					<div class="section-title">
						<h1>What We Can Do for You</h1>

					</div>
				</div>
			</div>

			<div class="row">
				{% for barbs in barb %}
				<div class="col-lg-3 col-sm-6 col-md-3">
					<div class="single-service">
						<img class="img-fluid" src="{{barbs.image.url}}" alt="" width="263" height="350">
						<h4>{{barbs.name}}</h4>
					</div>
				</div>
				{% endfor %}

		</div>
	</section>
	<!--================ End Service Area =================-->

	<!--================ Start Catalogue Area =================-->
	<section class="section-gap catalogue-area">
		<div class="container">
			<div class="row">
				<div class="col-lg-4 offset-lg-1 offset-md-2 col-sm-12 col-md-8">
					<div class="tab-area">
						<div class="tab-contact-wraper" id="horizontalTab">
							<h4>Select Your Style</h4>
							<p>Shaving</p>
							<div class="jq-tab-menu justify-content-center">
								<div class="jq-tab-title active" data-tab="1"><img src="{% static 'img/tab/icon1.png' %}" alt=""></div>
								<div class="jq-tab-title deff-bg1" data-tab="2"><img src="{% static 'img/tab/icon2.png' %}" alt=""></div>
								<div class="jq-tab-title" data-tab="3"><img src="{% static 'img/tab/icon3.png' %}" alt=""></div>
								<div class="jq-tab-title deff-bg1" data-tab="4"><img src="{% static 'img/tab/icon4.png' %}" alt=""></div>
							</div>

							<div class="jq-tab-content-wrapper">
								<div class="jq-tab-content active" data-tab="1">

									<a href="{% url 'haircut:gallery' %}" class="view-btn">View Gallery...</a>
								</div>
								<div class="jq-tab-content" data-tab="2">

									<a href="#" class="view-btn">View Gallery...</a>
								</div>
								<div class="jq-tab-content" data-tab="3">

									<a href="#" class="view-btn">View Gallery...</a>
								</div>
								<div class="jq-tab-content" data-tab="4">

									<a href="#" class="view-btn">View Gallery...</a>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>
	<!--================ End Catalogue Area =================-->

	<!--================ Start Team Area =================-->
	<section class="team-area section-gap">
		<div class="container">
			<div class="row justify-content-center">
				<div class="col-md-8 text-center">
					<div class="section-title">
						<h1>Stylist</h1>

					</div>
				</div>
			</div>
			<div class="row">
				<!-- single member -->
				<div class="col-lg-4 col-md-4">
					<div class="single-team-member">
						<div class="member-img">
							<img class="img-fluid" src="{% static 'img/barb/e1.jpg' %}" alt="" width="320" height="300">
						</div>

						<div class="proff">
							<h4>Promise</h4>
							<p>Head hair Cut Specialist</p>
						</div>
					</div>
				</div>

				<!-- single member -->
				<div class="col-lg-4 col-md-4">
					<div class="single-team-member">
						<div class="member-img">
							<img class="img-fluid" src="{% static 'img/barb/kr.jpg' %}" alt="" width="250" height="300" >
						</div>
						<div class="proff">
							<h4></h4>
							<p style="color:black;font-family:Lucida Console, Courier, monospace;">We have been in the industry for a long time and we know what customers need. A customer once testified" <em style="color:red">I had a weird style in my head and they gave just exacted what I expected. It was a moment of ecstasy.</em><br></p>
						</div>
					</div>
				</div>
        <!-- single member -->
				<div class="col-lg-4 col-md-4">
					<div class="single-team-member">
						<div class="member-img">
							<img class="img-fluid" src="{% static 'img/barb/et1.jpeg' %}" alt="" width="320" height="300">
						</div>
						<div class="proff">
							<h4></h4>
							<p></p>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>
	<!--================ End Team Area =================-->

	<!--================Testimonials Area =================-->
	<section class="testimonials-area section-gap-top">
		<div class="overlay overlay-bg"></div>
		<div class="container">
			<div class="text-center">
			<!--	<img class="quote-img" src="{% static 'img/testimonial/quote.png' %}" alt="">-->
			</div>
			<div class="testi-slider owl-carousel" data-slider-id="1">

				<div class="item">
					<div class="testi-item">
						<h4>Giannis</h4>
						<ul class="list">
							<li><a href="#"><i class="fa fa-star"></i></a></li>
							<li><a href="#"><i class="fa fa-star"></i></a></li>
							<li><a href="#"><i class="fa fa-star"></i></a></li>
							<li><a href="#"><i class="fa fa-star"></i></a></li>
							<li><a href="#"><i class="fa fa-star"></i></a></li>
						</ul>
						<div class="wow fadeIn" data-wow-duration="1s">
							<p>
                "Honestly I no longer get my hair or beard cut anywhere else. Promise makes me feel at home.
							</p>
						</div>
					</div>
				</div>
        <div class="item">
					<div class="testi-item">
						<h4>Emmy Novak</h4>
						<ul class="list">
							<li><a href="#"><i class="fa fa-star"></i></a></li>
							<li><a href="#"><i class="fa fa-star"></i></a></li>
							<li><a href="#"><i class="fa fa-star"></i></a></li>
							<li><a href="#"><i class="fa fa-star"></i></a></li>
							<li><a href="#"><i class="fa fa-star"></i></a></li>
						</ul>
						<div class="wow fadeIn" data-wow-duration="1s">
							<p>
								Wonderfully made my hair with good hospitality and affordable price.
							</p>
						</div>
					</div>
				</div>
				<div class="item">
					<div class="testi-item">
						<h4>Jane</h4>
						<ul class="list">
							<li><a href="#"><i class="fa fa-star"></i></a></li>
							<li><a href="#"><i class="fa fa-star"></i></a></li>
							<li><a href="#"><i class="fa fa-star"></i></a></li>
							<li><a href="#"><i class="fa fa-star"></i></a></li>
							<li><a href="#"><i class="fa fa-star"></i></a></li>
						</ul>
						<div class="wow fadeIn" data-wow-duration="1s">
							<p>
                "Promise does a fantastic job on anyone's hair! He did a lovely job on my hair and I will be continually coming back for my hair needs!!. Thanks again Promise!! - Jane
							</p>
						</div>
					</div>
				</div>
				<div class="item">
					<div class="testi-item">
						<h4>Faith</h4>
						<ul class="list">
							<li><a href="#"><i class="fa fa-star"></i></a></li>
							<li><a href="#"><i class="fa fa-star"></i></a></li>
							<li><a href="#"><i class="fa fa-star"></i></a></li>
							<li><a href="#"><i class="fa fa-star"></i></a></li>
							<li><a href="#"><i class="fa fa-star"></i></a></li>
						</ul>
						<div class="wow fadeIn" data-wow-duration="1s">
							<p>
                They gave me a great summer look. The braids were breath taking.
							</p>
						</div>
					</div>
				</div>
			</div>
			<div class="owl-thumbs d-flex justify-content-center" data-slider-id="1">

				
				<div class="owl-thumb-item">
					<div>
						<img class="img-fluid" src="{% static 'img/testimonial/t3.png' %}" alt="">
					</div>
					<div class="overlay overlay-grad"></div>
				</div>
				<div class="owl-thumb-item">
					<div>
						<img class="img-fluid" src="{% static 'img/testimonial/t4.png' %}" alt="">
					</div>
					<div class="overlay overlay-grad"></div>
				</div>
        <div class="owl-thumb-item">
          <div>
            <img class="img-fluid" src="{% static 'img/barb/e4.jpg' %}" alt="">
          </div>
          <div class="overlay overlay-grad"></div>
        </div>
			</div>
		</div>
	</section>
	<!--================End Testimonials Area =================-->

	<!--================Start Pricing Area =================-->
	<section class="price-area section-gap-top">
		<div class="container">
			<div class="row justify-content-center">
				<div class="col-lg-8 text-center">
					<div class="section-title">

					</div>
				</div>
			</div>
			<div class="row justify-content-center">
				<!-- single pricing -->
				<div class="col-lg-4 col-md-6 text-center">
					<div class="single-price">
						<div class="top-sec">
							<h4>Basic Hair Cut for Men</h4>
							<p>Standard Package</p>
						</div>
						<div class="bottom-sec">
							<h1></h1>
						</div>
						<div class="end-sec">
							<ul>
								<li>Basic hair Cut</li>
								<li>Basic Shave</li>
                <li>Dreadlock</li>

							</ul>
							<a class="primary-btn price-btn mt-40" href="{% url 'haircut:contact' %}">Order Now</a>
						</div>
					</div>
				</div>
				<!-- single pricing -->
				<div class="col-lg-4 col-md-6 text-center">
					<div class="single-price">
						<div class="top-sec">
							<h4>Basic Hairstyle for Ladies</h4>
							<p>Standard Package</p>
						</div>
						<div class="bottom-sec">
							<h1></h1>
						</div>
						<div class="end-sec">
							<ul>
								<li>Basic hair Cut</li>
								<li>Braiding</li>
                <li>Extensions/Weavons</li>
                <li>Dreadlock</li>

							</ul>
							<a class="primary-btn price-btn mt-40" href="{% url 'haircut:contact' %}">Order Now</a>
						</div>
					</div>
				</div>
				<!-- single pricing -->
				<div class="col-lg-4 col-md-6 text-center">
					<div class="single-price">
						<div class="top-sec">
							<h4>Home Service for Ladies</h4>
							<p>Standard Package</p>
						</div>
						<div class="bottom-sec">
							<h1></h1>
						</div>
						<div class="end-sec">
							<ul>
                <li>Haircut</li>
                <li>Braiding</li>
                <li>Extensions/Weavons</li>
                <li>Dreadlock</li>


							</ul>
							<a class="primary-btn price-btn mt-40" href="{% url 'haircut:contact' %}">Order Now</a>
						</div>
					</div>
				</div>
				<!-- single pricing -->
				<div class="col-lg-4 col-md-6 text-center">
					<div class="single-price active">
						<div class="top-sec">
							<h4>Home Service for Men</h4>
							<p>Standard Package</p>
						</div>
						<div class="bottom-sec">
							<h1></h1>
						</div>
						<div class="end-sec">
							<ul>
								<li>Basic hair Cut</li>
								<li>Basic Shave</li>
                <li>Dreadlock</li>

							</ul>
							<a class="primary-btn price-btn mt-40" href="{% url 'haircut:contact' %}">Order Now</a>
						</div>
					</div>
				</div>

					</div>
				</div>

	</section>
	<!--================Start Pricing Area =================-->


	<!--================ End Events Area =================-->


{% endblock %}